# Generated by Django 6.0.5 on 2026-06-09 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='is_dm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatgroupmembership',
            name='position_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chatgroupmembership',
            name='position_x',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='chatgroupmembership',
            name='position_y',
            field=models.FloatField(default=50.0),
        ),
        migrations.CreateModel(
            name='BlackboardNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackboard_notes', to='core.chatgroup')),
                ('updater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blackboard_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('pronouns', models.CharField(blank=True, max_length=40)),
                ('bio', models.TextField(blank=True, max_length=240)),
                ('status_text', models.CharField(blank=True, max_length=120)),
                ('status_mode', models.CharField(choices=[('online', 'Online'), ('idle', 'Idle'), ('dnd', 'Do not disturb'), ('invisible', 'Invisible'), ('offline', 'Offline')], default='online', max_length=12)),
                ('last_status_mode', models.CharField(blank=True, choices=[('online', 'Online'), ('idle', 'Idle'), ('dnd', 'Do not disturb'), ('invisible', 'Invisible'), ('offline', 'Offline')], default='online', max_length=12, null=True)),
                ('skin', models.CharField(blank=True, default='#facc15', max_length=7)),
                ('avatar_image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='UserDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=500)),
                ('file', models.FileField(blank=True, null=True, upload_to='drops/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='core.chatgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
    ]
