# Generated by Django 6.0.5 on 2026-06-02 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_chatgroup_id_alter_chatgroupmembership_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('pronouns', models.CharField(blank=True, max_length=40)),
                ('bio', models.TextField(blank=True, max_length=240)),
                ('status_text', models.CharField(blank=True, max_length=120)),
                ('status_mode', models.CharField(choices=[('online', 'Online'), ('idle', 'Idle'), ('dnd', 'Do not disturb'), ('invisible', 'Invisible')], default='online', max_length=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
