# Generated by Django 6.0.5 on 2026-06-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_author_to_updater'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='is_dm',
            field=models.BooleanField(default=False),
        ),
    ]
