# Generated by Django 5.2.12 on 2026-06-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_blackboardnote_id_alter_chatgroup_id_and_more'),
        ('core', '0008_chatgroup_is_dm'),
    ]

    operations = [
    ]
